[default]
description = "Default permissions for tauri-plugin-nostr-sync"
permissions = [
    "allow-publish",
    "allow-fetch",
    "allow-poll",
    "allow-sync-all",
    "allow-add-relay",
    "allow-remove-relay",
    "allow-get-relays",
    "allow-get-pubkey",
    "allow-get-status",
]
